[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
tokio = { version = "^1.44", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "~0.12", features = ["json"] }
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
