name: Build Release

permissions:
  contents: read

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build-linux-x86_64:
    name: Build linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Cache rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: temp

      - name: Build
        run: |
          cross build --target x86_64-unknown-linux-musl

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./target/x86_64-unknown-linux-musl/debug/tester
