name: Build Release

permissions:
  contents: read

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build-linux-x86_64:
    name: Build linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: |
          cross build --target x86_64-unknown-linux-musl

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./target/x86_64-unknown-linux-musl/debug/tester
