name: Build

permissions:
  contents: read

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build musl
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install packages
        run: |
          curl -LO https://github.com/cross-tools/musl-cross/releases/download/20250911/x86_64-unknown-linux-musl.tar.xz
          sudo mkdir -p /opt/x-tools
          sudo tar -xf x86_64-unknown-linux-musl.tar.xz -C /opt/x-tools
          echo CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc >> $GITHUB_ENV
          echo CC_x86_64_unknown_linux_musl=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc >> $GITHUB_ENV
          echo CXX_x86_64_unknown_linux_musl=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-g++ >> $GITHUB_ENV
          echo AR_x86_64_unknown_linux_musl=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-ar >> $GITHUB_ENV
          echo RANLIB_x86_64_unknown_linux_musl=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-ranlib >> $GITHUB_ENV
          echo STRIP_x86_64_unknown_linux_musl=/opt/x-tools/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-strip >> $GITHUB_ENV
          rustup target add x86_64-unknown-linux-musl

      - name: Build release
        run: |
          cargo build --target x86_64-unknown-linux-musl
