name: Build

permissions:
  contents: read

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build arm64
    runs-on: windows-11-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: cargo build

      - name: gdb
        run: gdb --version
