name: Build

permissions:
  contents: read

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y gdb

      - name: Build
        run: |
          cargo build
